services:
  customer.api:
    image: customer.api
    build:
      context: .
      dockerfile: DDD-Example.Customer/DDD-Example.Customer.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db-customer
    ports:
      - 5050-8080
    networks:
      - ddd
  vehicle.api:
    image: vehicle.api
    build:
      context: .
      dockerfile: DDD-Example.Vehicle/DDD-Example.Vehicle.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db-vehicle
    ports:
      - 5959-8080
    networks:
      - ddd
  rental.api:
    image: rental.api
    build:
      context: .
      dockerfile: DDD-Example.Rental/DDD-Example.Rental.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db-rental
    ports:
      - 6161-8080
    networks:
      - ddd
  db-customer:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - ddd
    shm_size: 128mb
    volumes:
      - ~/apps/ddd-example-customer:/var/lib/postgres2/data
    environment:
      - POSTGRES_USER=customer
      - POSTGRES_PASSWORD=customer
  db-vehicle:
    image: postgres
    ports:
      - 5433:5432
    networks:
      - ddd
    shm_size: 128mb
    volumes:
      - ~/apps/ddd-example-vehicle:/var/lib/postgres2/data
    environment:
      - POSTGRES_USER=vehicle
      - POSTGRES_PASSWORD=vehicle
  db-rental:
    image: postgres
    ports:
      - 5434:5432
    networks:
      - ddd
    shm_size: 128mb
    volumes:
      - ~/apps/ddd-example-rental:/var/lib/postgres2/data
    environment:
      - POSTGRES_USER=rental
      - POSTGRES_PASSWORD=rental
networks:
  ddd:
    name: ddd