services:
  customer.api:
    image: customer.api
    build:
      context: .
      dockerfile: DDD-Example.Customer.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080-8080
    networks:
      - ddd
  db-customer:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - ddd
    shm_size: 128mb
    volumes:
      - ~/apps/ddd-example-customer:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=customer
      - POSTGRES_PASSWORD=customer
networks:
  ddd:
    name: ddd